### PR TITLE
LOVE-1260 consistent case for parameter names

### PR DESCRIPTION
**Pull request by deepu105**
## Definition of Done

**General**
 - [ ] Branch is up-to-date with beta
 - [ ] Blueprint can be tested by Jenkins
 - [ ] Code is reviewed and tested by someone else in the team

**Testing**
- [ ] Works on Linux, Windows and Mac
- [ ] Works on all supported K8s flavors (Docker Desktop for mac/Windows, AWS EKS, Plain multinode K8s)
- [ ] Functionality is manually tested where not possible to automate
- [ ] Automated unit tests added and are green
- [ ] Automated integration tests added where needed and are green

### CODE REVIEW

**Comment by deepu105** [comment]
@eltonkevani there were some issues after merge few varibles were still being referred using lowercase and few expressions were wrong. I fixed those but now `xl-up/__test__/test-cases/provisioned-db/test-on-prem-xlr-mon.yaml` seems to be stuck, may be stuck on a question

**Comment by deepu105** [comment]
@eltonkevani seems like `PostgresqlWorkHostpath` is missing in most answer files, not sure if its neeed there or if the `PostgresqlWorkHostpath` param requires a better promptIf condition

**Comment by eltonkevani** [comment]
> @eltonkevani seems like `PostgresqlWorkHostpath` is missing in most answer files, not sure if its neeed there or if the `PostgresqlWorkHostpath` param requires a better promptIf condition

**Comment by eltonkevani** [comment]
> > @eltonkevani seems like `PostgresqlWorkHostpath` is missing in most answer files, not sure if its neeed there or if the `PostgresqlWorkHostpath` param requires a better promptIf condition

PostgresqlWorkHostpath is used only on local k8s use case. this is . why it it missing form most tests

**Pull request closed without merging**
